SELECT 
    ITE.NUNOTA AS "id",
    CAB.NUMNOTA,
    MAX(ITE.CODEMP) || ' - ' || MAX(EMP.RAZAOABREV) AS "empresa",
    MAX(CUS.DESCRCENCUS) AS "canal",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN 'VENDA' 
        WHEN CAB.TIPMOV = 'D' THEN 'DEVOLUÇÃO DE VENDA' 
        ELSE '' 
    END AS "tipo fiscal",

    MAX(PAR2.NOMEPARC) AS "transportadora",
    MAX(PAR.CODPARC) AS "id cliente",
    MAX(PAR.NOMEPARC) AS "cliente",
    MAX(CAB.CODVEND) AS "COD.VENDEDOR",
    MAX(VEN.APELIDO) AS "vendedor",

    -- Data de emissão em número Excel
    (TRUNC(MAX(CAB.DTNEG)) - TO_DATE('30/12/1899','DD/MM/YYYY')) AS "emissão",

    -- Totais e valores financeiros
    CASE 
        WHEN CAB.TIPMOV = 'V' THEN MAX(CAB.VLRNOTA) 
        WHEN CAB.TIPMOV = 'D' THEN MAX(CAB.VLRNOTA) * -1 
        ELSE NULL 
    END AS "total",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN MAX(CAB.VLRDESCTOT) 
        WHEN CAB.TIPMOV = 'D' THEN MAX(CAB.VLRDESCTOT) * -1 
        ELSE NULL 
    END AS "desconto",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN MAX(CAB.VLRFRETE) 
        WHEN CAB.TIPMOV = 'D' THEN MAX(CAB.VLRFRETE) * -1 
        ELSE NULL 
    END AS "frete",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN SUM(ITE.CUSTO) 
        WHEN CAB.TIPMOV = 'D' THEN SUM(ITE.CUSTO) * -1 
        ELSE NULL 
    END AS "custo",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN ((SUM(ITE.VLRUNIT * ITE.QTDNEG) - MAX(CAB.VLRDESCTOT)) - SUM(ITE.CUSTO)) 
        WHEN CAB.TIPMOV = 'D' THEN (((SUM(ITE.VLRUNIT * ITE.QTDNEG) - MAX(CAB.VLRDESCTOT)) - SUM(ITE.CUSTO)) * -1) 
        ELSE NULL 
    END AS "lucro líquido",

    -- Tipo de local baseado na origem
    CASE 
        WHEN ITE.CODLOCALORIG IN (101, 201, 301, 401, 901, 1001, 1101) THEN 'ESTOQUE'
        WHEN ITE.CODLOCALORIG IN (106, 202, 302, 402, 902, 1002, 1102) THEN 'AVARIA'
        ELSE 'OUTRO'
    END AS "Tipo Local",

    ITE.CODLOCALORIG AS "Local",

    MAX(CAB.VLRDESTAQUE) AS "Valor Destaque",
    MAX(CVP.CURVA) AS "curva",
    MAX(CID.NOMECID) AS "cidade",
    MAX(UF.DESCRICAO) AS "estado",
    TO_CHAR(MAX(CAB.DTNEG), 'WW') AS "semana",
    MAX(BAI.NOMEBAI) AS "bairro"

FROM TGFCAB CAB
LEFT JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TSIEMP EMP ON ITE.CODEMP = EMP.CODEMP
LEFT JOIN TSIUSU USU ON USU.CODUSU = ITE.CODUSU
LEFT JOIN TGFNAT NAT ON CAB.CODNAT = NAT.CODNAT
LEFT JOIN TSICUS CUS ON CAB.CODCENCUS = CUS.CODCENCUS
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TGFPAR PAR2 ON PAR2.CODPARC = CAB.CODPARCTRANSP
LEFT JOIN AD_CURVAVENPAR CVP ON CVP.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID
LEFT JOIN TSIUFS UF ON CID.UF = UF.CODUF
LEFT JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI

WHERE 
    CAB.TIPMOV IN ('V', 'D')
    AND CAB.CODTIPOPER IN (3021, 3022, 4021, 4201, 4056, 4057, 4025, 4028, 4029, 1201, 1952, 1954, 1951, 1957, 1960)
    AND ITE.NUNOTA <> 0
    AND ITE.NUNOTA NOT IN (9935, 10008, 14311)
    AND CAB.DTNEG BETWEEN TO_DATE('01/01/2025', 'DD/MM/YYYY') AND TRUNC(SYSDATE)
    AND CAB.STATUSNOTA = 'L'

GROUP BY 
    ITE.NUNOTA, CAB.NUMNOTA, CAB.TIPMOV, ITE.CODLOCALORIG

ORDER BY 
    ITE.NUNOTA ASC