SELECT
    PRO.ATIVO,
    PRO.CODPROD,
    PRO.REFERENCIA,
    PRO.DESCRPROD,
    PRO.MARCA,
    PRO.AD_QUALIDADE,
    PRO.AD_CORES,
    GRU.DESCRGRUPOPROD,
    PRO.USOPROD,
    PRO.AD_MODCOM,
    PRO.AD_MODELO,
    PRO.AD_ANOMODELO,
    PRO.AD_TIPOTELA,
    PRO.AD_DTCRIACAO,
    NVL(ABC.CURVA, 'D'),
    PRO.AD_CODPAI,
    PRO.AD_HERTZ,
    PRO.AD_COMPATIBILIDADE,
    PRO.CARACTERISTICAS,
    PRO.DTALTER,
    PRO.IMAGEM,
    PRO.NCM,
    PRO.AD_MODREF,
    PRO.AD_LINREF,
    PRO.AD_MACROGRUPO,
    PRO.AD_QUALIFORN,
    PRO.AD_DESCRFORN
    
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
LEFT JOIN AD_CABCPRO ABC ON PRO.CODPROD = ABC.CODPROD
WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11, 12, 13, 14)
    AND PRO.ATIVO = 'S'
ORDER BY PRO.CODPROD
