SELECT
    PRO.CODPROD AS "Código Interno",
    PRO.REFERENCIA AS "SKU",
    PRO.AD_MACROGRUPO AS "Macro Grupo",

    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0) AS "Estoque Total",

    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 1",
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 2",
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 3",

    CEIL((
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END)
    ) / 3) AS "Média Últimos 3 Meses",

    CEIL((
        COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0)
    ) / NULLIF(CEIL((
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END)
    ) / 3), 0) * 30) AS "Dias em Estoque",

    NVL((
        SELECT TRUNC(MAX(CAB2.DTNEG)) - TO_DATE('31/12/1899', 'DD/MM/YYYY') + 1
        FROM TGFITE ITE2
        INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
        WHERE ITE2.CODPROD = PRO.CODPROD
          AND CAB2.CODTIPOPER = 1301
          AND CAB2.STATUSNOTA IN ('L', 'A')
    ), TO_DATE('01/07/2024', 'DD/MM/YYYY') - TO_DATE('31/12/1899', 'DD/MM/YYYY')) AS "Data Última Compra (Excel)",

    CUST.CUSSEMICM AS "Custo Médio",

CASE
    -- PRODUTO NÃO VENDEU
    WHEN (
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END)
    ) = 0 THEN
        CASE
            WHEN (
                TO_DATE('31/12/1899', 'DD/MM/YYYY') + NVL((
                    SELECT TRUNC(MAX(CAB2.DTENTSAI)) - TO_DATE('31/12/1899', 'DD/MM/YYYY')
                    FROM TGFITE ITE2
                    INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
                    WHERE ITE2.CODPROD = PRO.CODPROD
                    AND CAB2.TIPMOV IN ('C', 'E')
                    AND CAB2.CODTIPOPER IN (1401, 4203)
                    AND CAB2.STATUSNOTA = 'L'
                ), TO_DATE('01/07/2024', 'DD/MM/YYYY') - TO_DATE('31/12/1899', 'DD/MM/YYYY'))
            ) >= TRUNC(SYSDATE - 90) THEN 'PVa'
            WHEN (
                TO_DATE('31/12/1899', 'DD/MM/YYYY') + NVL((
                    SELECT TRUNC(MAX(CAB2.DTENTSAI)) - TO_DATE('31/12/1899', 'DD/MM/YYYY')
                    FROM TGFITE ITE2
                    INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
                    WHERE ITE2.CODPROD = PRO.CODPROD
                    AND CAB2.TIPMOV IN ('C', 'E')
                    AND CAB2.CODTIPOPER IN (1401, 4203)
                    AND CAB2.STATUSNOTA = 'L'
                ), TO_DATE('01/07/2024', 'DD/MM/YYYY') - TO_DATE('31/12/1899', 'DD/MM/YYYY'))
            ) <= TRUNC(SYSDATE - 180) THEN 'CS-50'
            ELSE 'CS-50'
        END
    -- PRODUTO VENDEU
    ELSE
        CASE
            WHEN CEIL((
    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0)
) / NULLIF(CEIL((
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END)
) / 3), 0) * 30)
 >= 720 THEN 'CS-25'
            WHEN CEIL((
    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0)
) / NULLIF(CEIL((
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END)
) / 3), 0) * 30)
 >= 360 THEN 'CS'
            WHEN CEIL((
    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0)
) / NULLIF(CEIL((
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 60) AND TRUNC(SYSDATE - 31) THEN ITE.QTDNEG ELSE 0 END) +
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 90) AND TRUNC(SYSDATE - 61) THEN ITE.QTDNEG ELSE 0 END)
) / 3), 0) * 30)
 > 90 THEN 'CS+5'
            ELSE 'PV'
        END
END AS "Classificação Estoque"

FROM TGFPRO PRO
LEFT JOIN TGFITE ITE ON ITE.CODPROD = PRO.CODPROD
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
    AND CAB.TIPMOV = 'V'
    AND CAB.CODTIPOPER IN (3021, 3022, 4201, 4056, 4057, 4025, 4028, 4029, 4021, 1201)
    AND CAB.STATUSNOTA = 'L'
    AND CAB.DTNEG BETWEEN TO_DATE('01/07/2024', 'DD/MM/YYYY') AND TRUNC(SYSDATE - 1)

LEFT JOIN TGFEST EST  ON PRO.CODPROD = EST.CODPROD  AND EST.CODEMP  = '8' AND EST.CODLOCAL  = '101'
LEFT JOIN TGFEST EST4 ON PRO.CODPROD = EST4.CODPROD AND EST4.CODEMP = '2' AND EST4.CODLOCAL = '401'
LEFT JOIN TGFEST EST2 ON PRO.CODPROD = EST2.CODPROD AND EST2.CODEMP = '4' AND EST2.CODLOCAL IN ('301','101')
LEFT JOIN TGFEST EST3 ON PRO.CODPROD = EST3.CODPROD AND EST3.CODEMP = '3' AND EST3.CODLOCAL IN ('201','101')

LEFT JOIN (
    SELECT CUS.CODPROD, CUS.CUSSEMICM
    FROM TGFCUS CUS
    LEFT JOIN TGFCUS CUS2 ON CUS.CODPROD = CUS2.CODPROD AND CUS.DTATUAL < CUS2.DTATUAL
    WHERE CUS2.CODPROD IS NULL
) CUST ON CUST.CODPROD = PRO.CODPROD

WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11,12,13,14)
    AND PRO.ATIVO = 'S'

GROUP BY
    PRO.CODPROD,
    PRO.REFERENCIA,
    PRO.AD_MACROGRUPO,
    CUST.CUSSEMICM

ORDER BY 
  NVL((
    SELECT TRUNC(MAX(CAB2.DTNEG)) - TO_DATE('31/12/1899','DD/MM/YYYY') + 1
    FROM TGFITE ITE2
    INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
    WHERE ITE2.CODPROD = PRO.CODPROD
      AND CAB2.CODTIPOPER = 1301
      AND CAB2.STATUSNOTA IN ('L','A')
  ), TO_DATE('01/07/2024','DD/MM/YYYY') - TO_DATE('31/12/1899','DD/MM/YYYY')) DESC