SELECT DISTINCT
    ITE.NUNOTA AS "numero_unico",
    ITE.SEQUENCIA AS "sequencia_item",
    ITE.CODEMP || ' - ' || EMP.RAZAOABREV AS "empresa",
    (TRUNC(CAB.DTNEG) - TO_DATE('30/12/1899','DD/MM/YYYY')) AS "data_negociacao",

    CASE 
        WHEN CAB.CODTIPOPER IN  (2) THEN 'VENDAS SITE ARARANGUÁ'
        WHEN CAB.CODTIPOPER IN  (1) THEN 'VENDAS ARARANGUÁ'
        ELSE CUS5.DESCRCENCUS
    END AS "canal",

    CASE 
        WHEN CAB.TIPMOV = 'V' THEN 'VENDA' 
        WHEN CAB.TIPMOV = 'D' THEN 'DEVOLUÇÃO DE VENDA' 
        ELSE '' 
    END AS "tipo_fiscal",

    PRO.CODPROD AS "id_produto",

    CASE 
        WHEN CAB.TIPMOV = 'D' THEN ITE.QTDNEG * -1
        WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG
        ELSE 0
    END AS "quantidade",

    PAR.CODPARC AS "codigo_cliente",
    PAR.NOMEPARC AS "cliente",
    VEN.APELIDO AS "vendedor",

    CEIL(
        CASE 
            WHEN CAB.TIPMOV = 'D' THEN ((ITE.VLRUNIT * ITE.QTDNEG - ITE.VLRDESC) * -1)
            WHEN CAB.TIPMOV = 'V' THEN (ITE.VLRUNIT * ITE.QTDNEG - ITE.VLRDESC)
            ELSE 0
        END * 100
    ) / 100 AS "valor_total",

    CEIL(COALESCE(CUS.CUSSEMICM, 0) * 100) / 100 AS "custo_medio_unitario",

    CEIL(
        COALESCE(CUS.CUSSEMICM, 0) * 
        CASE 
            WHEN CAB.TIPMOV = 'D' THEN ITE.QTDNEG * -1
            WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG
            ELSE 0
        END * 100
    ) / 100 AS "custo_medio_total",

    CEIL(COALESCE(CAB.VLRDESCTOT, 0) / QTD.TOTAL_ITENS * 100) / 100 AS "valor_desconto_item",
    CEIL(COALESCE(CAB.VLRFRETE, 0) / QTD.TOTAL_ITENS * 100) / 100 AS "valor_frete_item",
    CEIL(COALESCE(CAB.VLRDESTAQUE, 0) / QTD.TOTAL_ITENS * 100) / 100 AS "valor_destaque_item"

FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
INNER JOIN TGFVEN VEN ON VEN.CODVEND = ITE.CODVEND
INNER JOIN TSIEMP EMP ON ITE.CODEMP = EMP.CODEMP
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TGFTOP TOP ON TOP.TIPMOV = CAB.TIPMOV
INNER JOIN TSICUS CUS5 ON CAB.CODCENCUS = CUS5.CODCENCUS

-- Custo atualizado com base no CUSSEMICM
LEFT JOIN TGFCUS CUS ON CUS.CODPROD = ITE.CODPROD
  AND CUS.DTATUAL = (
      SELECT MAX(CUS2.DTATUAL)
      FROM TGFCUS CUS2
      WHERE CUS2.CODPROD = ITE.CODPROD
        AND CUS2.DTATUAL <= CAB.DTNEG
  )

-- Subquery que conta quantos itens existem por nota
LEFT JOIN (
    SELECT NUNOTA, COUNT(*) AS TOTAL_ITENS
    FROM TGFITE
    GROUP BY NUNOTA
) QTD ON QTD.NUNOTA = ITE.NUNOTA

WHERE
    CAB.TIPMOV IN ('V', 'D')
    AND CAB.CODTIPOPER IN (3021, 3022, 4201, 4056, 4057, 4025, 4028, 4029, 4021, 1201, 1952, 1958, 1961)
    AND ITE.NUNOTA <> 0
    AND CAB.CODEMP IN (2, 3, 4, 8)
    AND CAB.DTNEG BETWEEN 
        TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM')
        AND LAST_DAY(ADD_MONTHS(SYSDATE, -1))
    AND CAB.STATUSNOTA = 'L'

ORDER BY 
    ITE.NUNOTA ASC, ITE.SEQUENCIA ASC