SELECT 
    PRO.CODPROD AS "Código interno",
    PRO.REFERENCIA AS "SKU",

    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) AS Saldo_Total,

    COALESCE(CUST.CUSSEMICM, 0) AS Custo_Medio,
    PRO.AD_MACROGRUPO AS "Macro Grupo"

FROM TGFPRO PRO

-- Estoques
LEFT JOIN TGFEST EST ON PRO.CODPROD = EST.CODPROD AND EST.CODEMP = '8' AND EST.CODLOCAL = '101'
LEFT JOIN TGFEST EST4 ON PRO.CODPROD = EST4.CODPROD AND EST4.CODEMP = '2' AND EST4.CODLOCAL = '401'
LEFT JOIN TGFEST EST2 ON PRO.CODPROD = EST2.CODPROD AND EST2.CODEMP = '4' AND EST2.CODLOCAL IN ('301', '101')
LEFT JOIN TGFEST EST3 ON PRO.CODPROD = EST3.CODPROD AND EST3.CODEMP = '3' AND EST3.CODLOCAL IN ('201', '101')

-- Preço regular
LEFT JOIN (
    SELECT 
        EXC1.CODPROD,
        EXC1.VLRVENDA,
        TAB1.CODTAB
    FROM TGFEXC EXC1
    INNER JOIN TGFTAB TAB1 ON EXC1.NUTAB = TAB1.NUTAB
    WHERE TAB1.DTVIGOR = (
        SELECT MAX(TAB.DTVIGOR)
        FROM TGFEXC EXC
        INNER JOIN TGFTAB TAB ON EXC.NUTAB = TAB.NUTAB
        WHERE 
            TAB.CODTAB = TAB1.CODTAB
            AND EXC.CODPROD = EXC1.CODPROD
            AND TAB.CODTAB NOT IN (0, 5)
    )
) PREC ON PRO.CODPROD = PREC.CODPROD

-- Custo médio
LEFT JOIN (
    SELECT 
        CUS.CODPROD,
        CUS.CUSSEMICM
    FROM TGFCUS CUS
    LEFT JOIN TGFCUS CUS2 
        ON CUS.CODPROD = CUS2.CODPROD AND CUS.DTATUAL < CUS2.DTATUAL
    WHERE CUS2.CODPROD IS NULL
) CUST ON PRO.CODPROD = CUST.CODPROD

WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11, 12, 13, 14)
    AND PRO.ATIVO = 'S'

GROUP BY
    PRO.CODPROD, PRO.REFERENCIA, PREC.VLRVENDA, CUST.CUSSEMICM, PRO.AD_MACROGRUPO

HAVING
    (
        COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
        COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0)
    ) > 0
    AND (PREC.VLRVENDA IS NULL OR PREC.VLRVENDA = 0)

ORDER BY
    PRO.CODPROD
