SELECT
    PAR.CODPARC AS "CODIGO",
    PAR.CODEMP AS "EMPRESA",
    CASE 
        WHEN PAR.CLIENTE = 'S' THEN 'Cliente' 
        WHEN PAR.FORNECEDOR = 'S' THEN 'FORNECEDOR' 
        WHEN PAR.VENDEDOR = 'S' THEN 'VENDEDOR' 
        WHEN PAR.TRANSPORTADORA = 'S' THEN 'TRANSPORTADORA' 
        WHEN PAR.USUARIO = 'S' THEN 'USUARIO' 
        ELSE '' 
    END AS TIPO,
    PAR.RAZAOSOCIAL AS "NOME",
    PAR.TELEFONE AS "TELEFONE",
    CID.NOMECID AS "CIDADE",
    PAR.CGC_CPF AS "CPF/CNPJ",
    PAR.TELEFONE AS "CELULAR",
    PAR.DTCAD AS "DATA DE CADASTRO",
    UFS.UF AS "ESTADO",
    BAI.NOMEBAI AS "BAIRRO",
    PAR.EMAIL AS "EMAIL",
    CVP.CURVA AS "CURVA",
    PAR.CEP AS "CEP",
    ENC.NOMEEND AS "ENDERECO" 

FROM TGFPAR PAR

INNER JOIN AD_CURVAVENPAR CVP ON CVP.CODPARC = PAR.CODPARC
LEFT JOIN TSICID CID ON PAR.CODCID = CID.CODCID
LEFT JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
LEFT JOIN TSIBAI BAI ON BAI.CODBAI = PAR.CODBAI
LEFT JOIN TSIEND ENC ON PAR.CODEND = ENC.CODEND 

WHERE PAR.CODPARC <> 0

ORDER BY PAR.RAZAOSOCIAL ASC