SELECT
    PRO.REFERENCIA AS "SKU",
    PRO.DESCRPROD AS "Produto",
    --CUST.CUSSEMICM AS "CUSTO_MEDIO",
    EXC_FRANQUIA.VLRVENDA AS "PRECO_FRANQUIA",
    EXC_ATACADO.VLRVENDA AS "PRECO_ATACADO",
    EXC_LOJA.VLRVENDA AS "PRECO_LOJA",
    --EXC_LOJA.VLRVENDA AS "SITE",
    CEIL(EXC_LOJA.VLRVENDA * 1.1261) AS "SITE_PIX",
    CEIL(EXC_LOJA.VLRVENDA * 1.1765) AS "B2B",
    CEIL(EXC_LOJA.VLRVENDA * 1.22) AS "CONSUMIDOR_FINAL"
FROM TGFPRO PRO

/*-- Join com custo médio sem ICMS
LEFT JOIN (
    SELECT
        CUS.CODPROD,
        CUS.CUSSEMICM
    FROM TGFCUS CUS
) CUST ON CUST.CODPROD = PRO.CODPROD*/

-- Preço Franquia (CODTAB = 4)
LEFT JOIN (
    SELECT 
        E.CODPROD,
        E.VLRVENDA
    FROM TGFEXC E
    JOIN TGFTAB T ON T.NUTAB = E.NUTAB
    WHERE T.CODTAB = 4
      AND E.NUTAB = (
          SELECT MAX(E2.NUTAB)
          FROM TGFEXC E2
          JOIN TGFTAB T2 ON T2.NUTAB = E2.NUTAB
          WHERE E2.CODPROD = E.CODPROD
            AND T2.CODTAB = 4
      )
) EXC_FRANQUIA ON EXC_FRANQUIA.CODPROD = PRO.CODPROD

-- Preço Atacado (CODTAB = 1)
LEFT JOIN (
    SELECT 
        E.CODPROD,
        E.VLRVENDA
    FROM TGFEXC E
    JOIN TGFTAB T ON T.NUTAB = E.NUTAB
    WHERE T.CODTAB = 1
      AND E.NUTAB = (
          SELECT MAX(E2.NUTAB)
          FROM TGFEXC E2
          JOIN TGFTAB T2 ON T2.NUTAB = E2.NUTAB
          WHERE E2.CODPROD = E.CODPROD
            AND T2.CODTAB = 1
      )
) EXC_ATACADO ON EXC_ATACADO.CODPROD = PRO.CODPROD

-- Preço Loja (CODTAB = 2)
LEFT JOIN (
    SELECT 
        E.CODPROD,
        E.VLRVENDA
    FROM TGFEXC E
    JOIN TGFTAB T ON T.NUTAB = E.NUTAB
    WHERE T.CODTAB = 2
      AND E.NUTAB = (
          SELECT MAX(E2.NUTAB)
          FROM TGFEXC E2
          JOIN TGFTAB T2 ON T2.NUTAB = E2.NUTAB
          WHERE E2.CODPROD = E.CODPROD
            AND T2.CODTAB = 2
      )
) EXC_LOJA ON EXC_LOJA.CODPROD = PRO.CODPROD

WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11, 12, 13, 14)
    AND PRO.ATIVO = 'S'
ORDER BY PRO.CODPROD