SELECT
    PRO.CODPROD AS "Código Interno",
    PRO.REFERENCIA AS "SKU",
    PRO.AD_MACROGRUPO AS "Macro Grupo",

    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) AS "Estoque principal",
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) AS "Estoque machine",
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) AS "Estoque oriental",
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0) AS "Estoque page",
    COALESCE(CEIL(MAX(EST5.ESTOQUE)), 0) AS "Estoque lutie",

    NVL((
        SELECT TRUNC(MAX(CAB2.DTNEG)) - TO_DATE('31/12/1899', 'DD/MM/YYYY') + 1
        FROM TGFITE ITE2
        INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA
        WHERE ITE2.CODPROD = PRO.CODPROD
          AND CAB2.CODTIPOPER = 1301
          AND CAB2.STATUSNOTA IN ('L', 'A')
    ), TO_DATE('01/07/2024', 'DD/MM/YYYY') - TO_DATE('31/12/1899', 'DD/MM/YYYY')) AS "Data Última Compra",

    CUST.CUSSEMICM AS "Custo Médio"

FROM TGFPRO PRO

LEFT JOIN TGFITE ITE ON ITE.CODPROD = PRO.CODPROD

LEFT JOIN TGFEST EST  ON PRO.CODPROD = EST.CODPROD  AND EST.CODEMP  = '8' AND EST.CODLOCAL  = '101'
LEFT JOIN TGFEST EST4 ON PRO.CODPROD = EST4.CODPROD AND EST4.CODEMP = '2' AND EST4.CODLOCAL = '401'
LEFT JOIN TGFEST EST2 ON PRO.CODPROD = EST2.CODPROD AND EST2.CODEMP = '4' AND EST2.CODLOCAL IN ('301','101')
LEFT JOIN TGFEST EST3 ON PRO.CODPROD = EST3.CODPROD AND EST3.CODEMP = '3' AND EST3.CODLOCAL IN ('201','101')
LEFT JOIN TGFEST EST5 ON PRO.CODPROD = EST5.CODPROD AND EST5.CODEMP = '3' AND EST5.CODLOCAL IN ('901','101')

LEFT JOIN (
    SELECT CUS.CODPROD, CUS.CUSSEMICM
    FROM TGFCUS CUS
    LEFT JOIN TGFCUS CUS2 ON CUS.CODPROD = CUS2.CODPROD AND CUS.DTATUAL < CUS2.DTATUAL
    WHERE CUS2.CODPROD IS NULL
) CUST ON CUST.CODPROD = PRO.CODPROD

WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11,12,13,14)
    AND PRO.ATIVO = 'S'

GROUP BY
    PRO.CODPROD,
    PRO.REFERENCIA,
    PRO.AD_MACROGRUPO,
    CUST.CUSSEMICM
