SELECT
    PRO.CODPROD AS "Código Interno",
    PRO.REFERENCIA AS "SKU",
    PRO.AD_MACROGRUPO AS "Macro Grupo",

    -- Estoque total somando os quatro estoques
    COALESCE(CEIL(MAX(EST.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST4.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST2.ESTOQUE)), 0) +
    COALESCE(CEIL(MAX(EST3.ESTOQUE)), 0) AS "Estoque Total",

    -- Vendas dos últimos 3 meses
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 1) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 1",
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 2) AND TRUNC(SYSDATE - 30 * 1 - 1) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 2",
    SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 3) AND TRUNC(SYSDATE - 30 * 2 - 1) THEN ITE.QTDNEG ELSE 0 END) AS "Vendas Mês 3",

    -- Média dos últimos 3 meses
    CEIL((
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 1) AND TRUNC(SYSDATE - 1) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 2) AND TRUNC(SYSDATE - 30 * 1 - 1) THEN ITE.QTDNEG ELSE 0 END) +
        SUM(CASE WHEN CAB.DTNEG BETWEEN TRUNC(SYSDATE - 30 * 3) AND TRUNC(SYSDATE - 30 * 2 - 1) THEN ITE.QTDNEG ELSE 0 END)
    ) / 3) AS "Média Últimos 3 Meses"

FROM TGFPRO PRO

LEFT JOIN TGFITE ITE ON ITE.CODPROD = PRO.CODPROD
LEFT JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA

LEFT JOIN TGFEST EST  ON PRO.CODPROD = EST.CODPROD  AND EST.CODEMP  = '8' AND EST.CODLOCAL  = '101'
LEFT JOIN TGFEST EST4 ON PRO.CODPROD = EST4.CODPROD AND EST4.CODEMP = '2' AND EST4.CODLOCAL = '401'
LEFT JOIN TGFEST EST2 ON PRO.CODPROD = EST2.CODPROD AND EST2.CODEMP = '4' AND EST2.CODLOCAL IN ('301', '101')
LEFT JOIN TGFEST EST3 ON PRO.CODPROD = EST3.CODPROD AND EST3.CODEMP = '3' AND EST3.CODLOCAL IN ('201', '101')

WHERE
    PRO.REFERENCIA <> '0'
    AND SUBSTR(PRO.CODGRUPOPROD, 0, 2) NOT IN (11, 12, 13, 14)
    AND PRO.ATIVO = 'S'
    AND PRO.AD_MACROGRUPO LIKE '%FRONTAL%' -- garante que filtre apenas as frontais
    AND CAB.TIPMOV = 'V'
    AND CAB.CODTIPOPER IN (3021, 3022, 4201, 4056, 4057, 4025, 4028, 4029, 4021, 1201)
    AND CAB.STATUSNOTA = 'L'
    AND CAB.DTNEG BETWEEN TO_DATE('01/07/2024', 'DD/MM/YYYY') AND TRUNC(SYSDATE - 1)

GROUP BY
    PRO.CODPROD,
    PRO.REFERENCIA,
    PRO.AD_MACROGRUPO

ORDER BY
    "Média Últimos 3 Meses" DESC

FETCH FIRST 25 ROWS ONLY